### ISSUE TITLE
compiling error for macOS

### ISSUE THREAD

**Issue by chaosma** [HarryR/ethsnarks-miximus#12]
When I try to compile on macOS Mojave it gave error, however it works fine on Ubuntu 18.04.
> make CMAKE=cmake 

This will have error "gmp.h" not found. But when I test with a simple cpp program with "#include <gmp.h>", it works fine and can find the gmp.h.

**Comment by HarryR** [comment]
Apologies, I updated the readme with better instructions specifically for OSX, Ubuntu and Redhat.

See: https://github.com/HarryR/ethsnarks-miximus/blob/838cff1cdf5a2a4196c2f20947abdcfd7471be32/README.md

You are missing the 'gmp' dependency in a location which can be found by cmake, this can be installed via Brew.

On OSX the following command will install all necessary dependencies using Brew.

    make -C ethsnarks mac-dependencies

You can install Brew via: https://brew.sh/

Dependencies required are:

 * gmp
 * libcrypto
 * boost
 * npm / nvm

-----------

It may be that gmp.h isn't in a location that's expected, I know that when installed via Brew it should work.

What is the location of gmp.h, and does cmake detect gmp properly on the first run?

Can you provide more details about where thr gmp dependency was installed from?

**Comment by chaosma** [comment]
After cmake, and when I run make, it gave me error like this:

> In file included from /Users/chaoma/ethsnarks-miximus/ethsnarks/depends/libsnark/depends/libff/libff/algebra/exponentiation/exponentiation.hpp:17:
/Users/chaoma/ethsnarks-miximus/ethsnarks/depends/libsnark/depends/libff/libff/algebra/fields/bigint.hpp:15:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
make[2]: *** [ethsnarks/CMakeFiles/ff.dir/depends/libsnark/depends/libff/libff/algebra/curves/alt_bn128/alt_bn128_g1.cpp.o] Error 1
make[1]: *** [ethsnarks/CMakeFiles/ff.dir/all] Error 2
make: *** [all] Error 2


I installed the gmp using "brew install gmp". 

> find /usr -name "gmp.h"
 /usr/local/include/gmp.h
/usr/local/Cellar/gmp/6.1.2_2/include/gmp.h

Then I added this location into $PATH. But when I test with a simple c program with header "#include <gmp.h>". It can be compiled.

**Comment by HarryR** [comment]
Can you paste the output of:

    make VERBOSE=1

This will display the compiler arguments.

If dependency was installed after running cmake for the first time, you may need to remove the build or .build directory and re-run cmake?

I'm unsure of why its not finding gmp.h, it builds on Travis/OSX and locally on Mac, but I'm sure we can figure out why its not working for you.

**Comment by chaosma** [comment]
Thanks! Here is the log:

```
/Library/Developer/CommandLineTools/usr/bin/make -C .build/
/usr/local/Cellar/cmake/3.13.0/bin/cmake -S/Users/chaoma/ethsnarks-miximus/circuit -B/Users/chaoma/ethsnarks-miximus/.build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.13.0/bin/cmake -E cmake_progress_start /Users/chaoma/ethsnarks-miximus/.build/CMakeFiles /Users/chaoma/ethsnarks-miximus/.build/CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make -f ethsnarks/depends/CMakeFiles/SHA3IUF.dir/build.make ethsnarks/depends/CMakeFiles/SHA3IUF.dir/depend
cd /Users/chaoma/ethsnarks-miximus/.build && /usr/local/Cellar/cmake/3.13.0/bin/cmake -E cmake_depends "Unix Makefiles" /Users/chaoma/ethsnarks-miximus/circuit /Users/chaoma/ethsnarks-miximus/ethsnarks/depends /Users/chaoma/ethsnarks-miximus/.build /Users/chaoma/ethsnarks-miximus/.build/ethsnarks/depends /Users/chaoma/ethsnarks-miximus/.build/ethsnarks/depends/CMakeFiles/SHA3IUF.dir/DependInfo.cmake --color=
/Library/Developer/CommandLineTools/usr/bin/make -f ethsnarks/depends/CMakeFiles/SHA3IUF.dir/build.make ethsnarks/depends/CMakeFiles/SHA3IUF.dir/build
make[3]: Nothing to be done for `ethsnarks/depends/CMakeFiles/SHA3IUF.dir/build'.
[  6%] Built target SHA3IUF
/Library/Developer/CommandLineTools/usr/bin/make -f ethsnarks/CMakeFiles/ff.dir/build.make ethsnarks/CMakeFiles/ff.dir/depend
cd /Users/chaoma/ethsnarks-miximus/.build && /usr/local/Cellar/cmake/3.13.0/bin/cmake -E cmake_depends "Unix Makefiles" /Users/chaoma/ethsnarks-miximus/circuit /Users/chaoma/ethsnarks-miximus/ethsnarks /Users/chaoma/ethsnarks-miximus/.build /Users/chaoma/ethsnarks-miximus/.build/ethsnarks /Users/chaoma/ethsnarks-miximus/.build/ethsnarks/CMakeFiles/ff.dir/DependInfo.cmake --color=
/Library/Developer/CommandLineTools/usr/bin/make -f ethsnarks/CMakeFiles/ff.dir/build.make ethsnarks/CMakeFiles/ff.dir/build
[ 13%] Building CXX object ethsnarks/CMakeFiles/ff.dir/depends/libsnark/depends/libff/libff/algebra/curves/alt_bn128/alt_bn128_g1.cpp.o
cd /Users/chaoma/ethsnarks-miximus/.build/ethsnarks && /Library/Developer/CommandLineTools/usr/bin/c++  -DBINARY_OUTPUT -DCURVE_ALT_BN128 -DMONTGOMERY_OUTPUT -DNO_PROCPS -DNO_PT_COMPRESSION=1 -DSHA3_USE_KECCAK=1 -DUSE_ASM -I/Users/chaoma/ethsnarks-miximus/ethsnarks/depends/libsnark -I/Users/chaoma/ethsnarks-miximus/ethsnarks/depends/libsnark/depends/libff -I/Users/chaoma/ethsnarks-miximus/ethsnarks/depends/libsnark/depends/libfqfft  -Wall -Wfatal-errors -Wno-unused-variable  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -fPIC -std=gnu++11 -o CMakeFiles/ff.dir/depends/libsnark/depends/libff/libff/algebra/curves/alt_bn128/alt_bn128_g1.cpp.o -c /Users/chaoma/ethsnarks-miximus/ethsnarks/depends/libsnark/depends/libff/libff/algebra/curves/alt_bn128/alt_bn128_g1.cpp
```

**Comment by chaosma** [comment]
The gmp information from the CMakeCache.txt is:

`//Path to a file.
GMPXX_INCLUDE_DIR:PATH=/usr/local/include

//Path to a library.
GMPXX_LIBRARY:FILEPATH=/usr/local/lib/libgmpxx.dylib

//Path to a file.
GMP_INCLUDE_DIR:PATH=/usr/local/include

//Path to a library.
GMP_LIBRARY:FILEPATH=/usr/local/lib/libgmp.dylib`

And I found they are there:
`find /usr/local/lib -name "libgmp*"
/usr/local/lib/libgmpxx.4.dylib
/usr/local/lib/libgmp.a
/usr/local/lib/libgmp.dylib
/usr/local/lib/libgmpxx.a
/usr/local/lib/libgmp.10.dylib
/usr/local/lib/libgmpxx.dylib`

**Comment by HarryR** [comment]
Thanks for responding with the information, I'm still unsure of why you can compile a single file and it finds `gmp.h` but when building it's unable to find it, but my thoughts are:

Could you modify `ethsnarks/CMakeLists.txt` quickly, just to see if the following fixes it?

Find line 256:
```
target_include_directories(ff PUBLIC
  ${DEPENDS_DIR_LIBSNARK} ${DEPENDS_DIR_LIBFF} ${DEPENDS_DIR_LIBFQFFT})
```

And add `${GMP_INCLUDE_DIR}` 

e.g. 
```
target_include_directories(ff PUBLIC
  ${GMP_INCLUDE_DIR} ${DEPENDS_DIR_LIBSNARK} ${DEPENDS_DIR_LIBFF} ${DEPENDS_DIR_LIBFQFFT})
```

If that fixes it, but you get build errors elsewhere due to missing 'gmp.h', you would need to do the same on line 276 (`ff INTERFACE`)

**Comment by chaosma** [comment]
Cool, it works! So the reason is that makefile didn't include the folder of gmp.h correctly?

**Comment by HarryR** [comment]
Seems like it.

I'll add this into the `ethsnarks` project shortly and close this issue (notifying you) when that's done.

**Comment by HarryR** [comment]
Apologies for the delay in closing the ticket.

Somebody else ran into the same problem with Ethsnarks on OSX Mojave.

I've included the fixes in the `master` branch, along with Travis CI builds for OSX 10.14.

I will update the miximus repository to use the latest version of ethsnarks and close this ticket off.
